### ISSUE TITLE
Newly joined rooms do not carry minibox behavior when hovered

### ISSUE THREAD

**Issue by Unihedro** [KeyboardFire/stackexchange-chatception#1]
Already am in Alpha Centauri:
![](http://i.imgur.com/WL1pOcI.png)
Joined just now Gamma Centauri:
![](http://i.imgur.com/TZGavI4.png)
Hovering over Gamma Centauri does not give a box for chatting.
![](http://i.imgur.com/ZEh46Fk.png)
Hovering over Alpha Centauri does though, as expected.
![](http://i.imgur.com/NjJh5Nq.png)

**Comment by Unihedro** [comment]
For now, refreshing seems to fix the behavior.

**Comment by tckmn** [comment]
Bug has been unbugged.
