### ISSUE TITLE
Overscrolling on mini-chatbox will scroll main chat room

### ISSUE THREAD

**Issue by andrew-tc** [KeyboardFire/stackexchange-chatception#2]
When the scrollbar inside mini-chatbox is already on the top/bottom, scrolling up/down on it will scroll main chat room instead. My expectation is to just do nothing (prevent scrolling).

Given current implementation that the newest message inside mini-chatbox is on top, while it's on bottom for main chat room, accidental overscrolling might be inconvenience for user.

**Comment by tckmn** [comment]
I have moved the newest message (and the "send message" field) to the bottom, so this shouldn't be too severe of an issue any longer.
