### ISSUE TITLE
Script has no effect if it's not focused when the chat page is loaded.

### ISSUE THREAD

**Issue by Unihedro** [KeyboardFire/stackexchange-chatception#3]
When I right click to open a chat room in a new tab in background, no widgets are activated whatsoever.

**Comment by tckmn** [comment]
Can't reproduce this on Firefox 37.0.1 on Ubuntu.

**Comment by Unihedro** [comment]
It's still there.

**Comment by Unihedro** [comment]
Taken on Google Chrome 42.0.2311.135 on Ubuntu:

![](http://i.imgur.com/KQdaAVg.gif)

**Comment by michaelpri10** [comment]
I was able to reproduce this on Chrome, and I fixed it with my last commit
