### ISSUE TITLE
Don't give me an option to edit messages I didn't make when I'm not a moderator.

### ISSUE THREAD

**Issue by Unihedro** [KeyboardFire/stackexchange-chatception#4]
There's just no reason to. It won't work anyway.

![](http://i.imgur.com/1q2IQbN.png)

**Comment by tckmn** [comment]
Same goes for delete. The reason I haven't done this is basically because I'm lazy. Shall be fixified soon.

**Comment by tckmn** [comment]
This has been fixed, except that it still shows these buttons for moderators (you can also no longer reply to your own messages).
