### ISSUE TITLE
Script "in title unseen display" should not render negative values due to dismissing pings

### ISSUE THREAD

**Issue by Unihedro** [KeyboardFire/stackexchange-chatception#6]
![](http://i.imgur.com/4snUpQa.png)

**Comment by tckmn** [comment]
I've experienced this problem before, but I could never reliably reproduce it. Would you mind giving some step-by-step instructions on how to trigger the bug, if you've figured it out?

**Comment by tckmn** [comment]
This got fixed in some commit or other. ¯\_(ツ)_/¯
