### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by normalhuman** [KeyboardFire/stackexchange-chatception#8]
When a chatroom is open over HTTPS, Chatception is blocked (at least in Chrome) because of mixed content:

> jquery.min.js:4 Mixed Content: The page at 'https://chat.stackexchange.com/rooms/11540/charcoal-hq' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://chat.stackexchange.com/chats/30985/events'. This request has been blocked; the content must be served over HTTPS.

**Comment by tckmn** [comment]
Fixed in #9 (thanks!).
